//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveLocationRow
    {
        public long InventoryRowGUID { get; set; }
        public string LocationNumber { get; set; }
        public Nullable<int> RowNumber { get; set; }
        public Nullable<int> NumberOfPartNumbers { get; set; }
        public Nullable<int> NumberOfStacks { get; set; }
        public Nullable<int> PalletCount { get; set; }
    }
}
