//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveInventoryLocation
    {
        public long InventoryLocationGUID { get; set; }
        public string LocationNumber { get; set; }
        public Nullable<int> NumberOfRows { get; set; }
    }
}
