//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveTrailerList
    {
        public int TrailerGUID { get; set; }
        public string TrailerNumber { get; set; }
        public string TrailerStatus { get; set; }
        public string LoadStatus { get; set; }
        public string Customer { get; set; }
        public string OrderDate { get; set; }
        public string OrderNumber { get; set; }
        public string LocationStatus { get; set; }
        public string TrailerLocation { get; set; }
        public string Notes { get; set; }
        public string Tags { get; set; }
        public string DateModified { get; set; }
    }
}
