//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeViolation
    {
        public long CodeViolationGUID { get; set; }
        public Nullable<long> SafetyConcernGUID { get; set; }
        public string Type { get; set; }
        public string OshaCode { get; set; }
        public string Description { get; set; }
        public string TypeSubType { get; set; }
    }
}
