//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersAndVendor
    {
        public int CompanyGUID { get; set; }
        public string CustomerNumber { get; set; }
        public string VendorNumber { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string SortType { get; set; }
        public string EmailAddresses { get; set; }
        public string SortTypeDescription { get; set; }
        public string PhoneNumber { get; set; }
        public string ContactName { get; set; }
        public string PayoutDescription { get; set; }
    }
}
