//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverConcern
    {
        public int DriverConcernGUID { get; set; }
        public string DriverSignedIn { get; set; }
        public string Customer { get; set; }
        public string DateTaken { get; set; }
        public string Notes { get; set; }
    }
}
