//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverConcernImage
    {
        public int DriverConcernImageGUID { get; set; }
        public Nullable<int> DriverConcernGUID { get; set; }
        public string ImagePath { get; set; }
        public string Note { get; set; }
    }
}
