//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InactiveTrailerList
    {
        public int TrailerGUID { get; set; }
        public string TrailerNumber { get; set; }
        public string DOTDate { get; set; }
        public string TrailerStatus { get; set; }
        public string Leased { get; set; }
        public string InsuranceCard { get; set; }
        public string Insured { get; set; }
        public string Title { get; set; }
        public string PlateNumber { get; set; }
        public string VinNumber { get; set; }
        public string Manufacturer { get; set; }
        public string ManufactureYear { get; set; }
        public string TrailerLength { get; set; }
        public string Issues { get; set; }
        public string DateModified { get; set; }
        public string TrailerLocation { get; set; }
    }
}
