//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryRowStack
    {
        public long InventoryRowStackGUID { get; set; }
        public Nullable<long> InventoryRowGUID { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> StackQuantity { get; set; }
        public Nullable<int> StackNumber { get; set; }
    }
}
