//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterStacksTest
    {
        public long StackGUID { get; set; }
        public Nullable<long> SortGUID { get; set; }
        public Nullable<int> StackNumber { get; set; }
        public string PartNumber { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> PeopleOnStack { get; set; }
        public string UserSignedIn { get; set; }
        public string PalletNote { get; set; }
        public Nullable<bool> IsSplit { get; set; }
        public string SplitFrom { get; set; }
    }
}
