//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PalletPrice
    {
        public long PalletPriceGUID { get; set; }
        public string VendorNumber { get; set; }
        public string VendorName { get; set; }
        public string PartNumber { get; set; }
        public string Description { get; set; }
        public string PurchasePrice { get; set; }
    }
}
