//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PalletType
    {
        public long PalletTypeGUID { get; set; }
        public string PartNumber { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string TagsRequired { get; set; }
        public string PutAwayLocation { get; set; }
        public string Status { get; set; }
    }
}
