//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayoutsBackup
    {
        public long PayoutGUID { get; set; }
        public Nullable<long> SortGUID { get; set; }
        public string TrailerNumber { get; set; }
        public string Vendor { get; set; }
        public Nullable<int> VendorNumber { get; set; }
        public string OrderNumber { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public string PackingListNumber { get; set; }
        public string BillOfLading { get; set; }
        public string Status { get; set; }
        public string DateArrived { get; set; }
        public Nullable<double> TimeToSort { get; set; }
        public string DateCompleted { get; set; }
    }
}
