//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionEmployee
    {
        public int ProductionEmployeeGUID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> EmployeeBadgeNumber { get; set; }
        public string NameAndBadgeNumber { get; set; }
        public string Status { get; set; }
    }
}
