//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SafetyConcern
    {
        public long SafetyConcernGUID { get; set; }
        public string Area { get; set; }
        public string ConditionNoted { get; set; }
        public string CodeViolation { get; set; }
        public string CodeViolation2 { get; set; }
        public string CodeViolation3 { get; set; }
        public string CorrectiveActionMeasure { get; set; }
        public string Severity { get; set; }
        public string ImagePath { get; set; }
    }
}
