//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SafetyConcern
    {
        public long SafetyConcernGUID { get; set; }
        public string Area { get; set; }
        public string SubArea { get; set; }
        public string ConditionNoted { get; set; }
        public string CorrectiveAction { get; set; }
        public string Severity { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> ViolationCount { get; set; }
        public string Status { get; set; }
        public string DateOpened { get; set; }
        public string DateClosed { get; set; }
    }
}
