//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SortImage
    {
        public long SortImageGUID { get; set; }
        public Nullable<long> SortGUID { get; set; }
        public Nullable<int> StackNumber { get; set; }
        public string TakenBy { get; set; }
        public string Notes { get; set; }
        public string ImagePath { get; set; }
        public string DateTaken { get; set; }
    }
}
