//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SortListTest
    {
        public long SortGUID { get; set; }
        public string TrailerNumber { get; set; }
        public string Customer { get; set; }
        public string Vendor { get; set; }
        public string OrderNumber { get; set; }
        public string SortType { get; set; }
        public string LoadStatus { get; set; }
        public string DateArrived { get; set; }
        public Nullable<int> MaxStackNumber { get; set; }
        public Nullable<int> NumberOfPeopleToStart { get; set; }
        public Nullable<double> TimeToSort { get; set; }
        public string Status { get; set; }
        public string SortChoice { get; set; }
    }
}
